"""https://www.hackerrank.com/contests/projecteuler/challenges/euler011/problem

The sequence of triangle numbers is generated by adding the natural numbers.  So the 7th triangle number
would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28

THe first ten terms would be 1, 3,6, 10, 15, 21, 28, 36, 45, 55, ...

28 is the first triangle number to have over five divisors (with 6).

What is the value of the first triangle number to have over N divisors?

1 <= number of test cases <= 10
1 <= N <= 1000

"""

import sys
sys.stdin = open(__file__.replace('.py', ' - Inputs.txt'))  # Simulate inputs from stdin - remove this on Hackerrank


def first_triangle_num_w_divisors(n: int) -> int:
    """
    return the first triangle number having more than n divisors
    """
    pass


if __name__ == '__main__':
    for _ in range(int(input())):
        print(first_triangle_num_w_divisors(int(input())))
